# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Worcester Technical High School
email: info@techhigh.us
description: >- # this means to ignore newlines until "baseurl:"
  Worcester Technical High School is a Chapter 74 Vocational School in Central Massachusetts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Google analytics
google_analytics: UA-83881166-1

# Social media vars
# twitter_username: jekyllrb
twitter_username_wths: wteagles
twitter_username_wps: worcesterpublic
# github_username:  worcestertechnicalhighschool

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections: 
  sections:
    sort_by: priority
    # Contains all the major groups of pages
    output: true
    permalink: /:path/

  student_life:
    # Clubs, news, sports, etc
    output: true
    permalink: /student-life/:path/

  parents_and_community:
    # Alumni, announcements, etc
    output: true
    permalink: /parents-and-community/:path/
  
  public_services:
    # Bank, restaurant, etc
    output: true
    permalink: /public-services/:path/

  technical_areas:
    # Academies: Allied, ITBS, etc
    output: true
    permalink: /technical-areas/:path/

  academics:
    # Academic pages: ELA, Math, etc
    output: true
    permalink: /academics/:path/
  
  learn_more:
    # Admin, admissions, etc
    output: true
    permalink: /learn-more/:path/
  
  # Shops are in the academy collections
  alden_academy:
    output: true
    permalink: /technical-areas/alden-academy/:path/
  allied_academy:
    output: true
    permalink: /technical-areas/allied-academy/:path/
  construction_academy:
    output: true
    permalink: /technical-areas/construction-academy/:path/
  itbs_academy:
    output: true
    permalink: /technical-areas/itbs-academy/:path/
  
  # Featured news collection
  featured_news:
    output: true
    permalink: /news/:path/
    

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
